#! /usr/bin/env python

import sys

if __name__ == "__main__":
    # Exclude the first argument because it is the script name
    stack = sys.argv[1:]

    if "".join(stack).strip() == "":
        print("No strings provided. Please provide a list of strings as arguments.", file=sys.stderr)
        exit(1)

    *rest, word = stack
    letters = [letter for letter in word]
    stack = rest + [f"[ {' '.join(letters)} ]"]
    print(*stack, end="", flush=True)
    exit(0)
