name: Docker Image CI

on:
  push:
    branches: [ "main", "pattern-matching" ]
  pull_request:
    branches: [ "main", "pattern-matching" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag consize-py
    - name: Run unit-tests
      run: docker run -i consize-py "python -m unittest tests/test.py"
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: workspace_artifacts
        path: ${{ github.workspace }}
