name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag consize-py
    - name: Run prelude tests
      run: docker run -i consize-py "\ prelude/prelude.txt run \ prelude/prelude-test.txt run"
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: workspace_artifacts
        path: ${{ github.workspace }}
